### ISSUE TITLE
shape mismatch when run ./rfcn/demo.py

### ISSUE THREAD

**Issue by catsdogone** [bharatsingh430/Deformable-ConvNets#4]
@bharatsingh430 When run ./rfcn/demo.py, in order to load your trained params: rfcn_dcn_coco-0008.params, I change the line 95 from:
arg_params, aux_params = load_param(cur_path + '/../model/' + ('rfcn_dcn_coco' if not args.rfcn_only else 'rfcn_coco'), 0, process=True)
to:
arg_params, aux_params = load_param(cur_path + '/../model/' + ('rfcn_dcn_coco' if not args.rfcn_only else 'rfcn_coco'), 8, process=True)
While this is an error: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (60,) to.shape=(48,)
Is it due to the parameters of anchor? How should I change the config file.
Thanks.

**Comment by bharatsingh430** [comment]
can you change number of anchors to 15?

**Comment by catsdogone** [comment]
@bharatsingh430 Thanks very much for your quick response. I have changed the number of anchors to 15 and the demo file can work. While I am not sure about the scale and ratio. I set the scale = [4,8,16,32,64]and ratio=[0.5,1,2],the result is not good under this parameter setting.

**Comment by bharatsingh430** [comment]
you should measure recall of anchors with ground truth at the image scale you are using and then set them. setting it arbitrarily would lead to bad performance. i have set it to [2,4,8,16,32]
